# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsBEfINBZM3E-s0ERP5qTLdCCQf2rjJZ
"""

def minimax(node, maximizing):
    if not node.get("children"):
        return node["value"]

    if maximizing:
        best = float("-inf")
        for child in node["children"]:
            value = minimax(child, False)
            best = max(best, value)
        return best
    else:
        best = float("inf")
        for child in node["children"]:
            value = minimax(child, True)
            best = min(best, value)
        return best


def leaf(v):
    return {"value": v, "children": []}

# ---------------------------------------------------------------
# Example 1 — small tree (8 leaves)
# ---------------------------------------------------------------
def build_tree_1():
    A = {"children": [leaf(10), leaf(9)]}
    B = {"children": [leaf(14), leaf(18)]}
    C = {"children": [leaf(5), leaf(4)]}
    D = {"children": [leaf(8), leaf(3)]}
    L = {"children": [A, B]}
    R = {"children": [C, D]}
    root = {"children": [L, R]}
    return root

# ---------------------------------------------------------------
# Example 2 — wider tree (14 leaves)
# ---------------------------------------------------------------
def build_tree_2():
    Ma = {"children": [leaf(5), leaf(6)]}
    Mb = {"children": [leaf(7), leaf(4), leaf(5)]}
    Mc = {"children": [leaf(3), leaf(6)]}
    Md = {"children": [leaf(6), leaf(9), leaf(7)]}
    Me = {"children": [leaf(5), leaf(9)]}
    Mf = {"children": [leaf(8), leaf(6)]}
    M1 = {"children": [Ma, Mb]}
    M2 = {"children": [Mc, Md]}
    M3 = {"children": [Me, Mf]}
    root = {"children": [M1, M2, M3]}
    return root

tree1 = build_tree_1()
    print("Example 1 result:", minimax(tree1, maximizing=True))  # 10

    tree2 = build_tree_2()
    print("Example 2 result:", minimax(tree2, maximizing=True))  # 8