# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UR-_eZtRm1nYXurri3-BNsEvyEAgnXYg
"""

def alpha_beta(node, alpha, beta, maximizing):
    if not node.get("children"):
        return node["value"]

    if maximizing:
        best = float("-inf")
        for child in node["children"]:
            value = alpha_beta(child, alpha, beta, False)
            best = max(best, value)
            alpha = max(alpha, best)
            if beta <= alpha:
                break  # beta cut-off: remaining children pruned
        return best
    else:
        best = float("inf")
        for child in node["children"]:
            value = alpha_beta(child, alpha, beta, True)
            best = min(best, value)
            beta = min(beta, best)
            if beta <= alpha:
                break  # alpha cut-off: remaining children pruned
        return best


def leaf(v):
    return {"value": v, "children": []}

# ---------------------------------------------------------------
# Example 1 — small tree (8 leaves)
# ---------------------------------------------------------------
def build_tree_1():
    A = {"children": [leaf(10), leaf(9)]}
    B = {"children": [leaf(14), leaf(18)]}
    C = {"children": [leaf(5), leaf(4)]}
    D = {"children": [leaf(8), leaf(3)]}
    L = {"children": [A, B]}
    R = {"children": [C, D]}
    root = {"children": [L, R]}
    return root

# ---------------------------------------------------------------
# Example 2 — wider tree (14 leaves)
# ---------------------------------------------------------------
def build_tree_2():
    Ma = {"children": [leaf(5), leaf(6)]}
    Mb = {"children": [leaf(7), leaf(4), leaf(5)]}
    Mc = {"children": [leaf(3), leaf(6)]}
    Md = {"children": [leaf(6), leaf(9), leaf(7)]}
    Me = {"children": [leaf(5), leaf(9)]}
    Mf = {"children": [leaf(8), leaf(6)]}
    M1 = {"children": [Ma, Mb]}
    M2 = {"children": [Mc, Md]}
    M3 = {"children": [Me, Mf]}
    root = {"children": [M1, M2, M3]}
    return root

if __name__ == "__main__":
    tree1 = build_tree_1()
    result1 = alpha_beta(tree1, float("-inf"), float("inf"), maximizing=True)
    print("Example 1 result:", result1)  # 10 (same as minimax, fewer nodes visited)

    tree2 = build_tree_2()
    result2 = alpha_beta(tree2, float("-inf"), float("inf"), maximizing=True)
    print("Example 2 result:", result2)  # 8 (same as minimax, fewer nodes visited)